#!/bin/bash

# Script to help set package visibility to public
# This script provides instructions since package visibility must be set via GitHub UI

echo "======================================"
echo "Docker-Nodejs Package Visibility Setup"
echo "======================================"
echo ""
echo "To fix 'unauthorized' errors when pulling Docker images, you need to make the packages public."
echo ""
echo "Follow these steps:"
echo ""
echo "1. Go to: https://github.com/users/trisout78/packages"
echo "2. For each nodejs package (nodejs_20, nodejs_21, nodejs_22, nodejs_23):"
echo "   a. Click on the package name"
echo "   b. Go to 'Package settings' tab"
echo "   c. Scroll down to 'Danger Zone'"
echo "   d. Click 'Change visibility'"
echo "   e. Select 'Public'"
echo "   f. Confirm the change"
echo ""
echo "Alternative: If you have GitHub CLI installed, you can use:"
echo "gh api --method PATCH /user/packages/container/nodejs_20 --field visibility=public"
echo "gh api --method PATCH /user/packages/container/nodejs_21 --field visibility=public"
echo "gh api --method PATCH /user/packages/container/nodejs_22 --field visibility=public"
echo "gh api --method PATCH /user/packages/container/nodejs_23 --field visibility=public"
echo ""
echo "After making packages public, users can pull images without authentication:"
echo "docker pull ghcr.io/trisout78/nodejs_23:latest"
echo ""
echo "======================================"